### ISSUE TITLE
1.1.0-beta.0: graphql comments are being deleted in the merged schema if you are using # instead of """

### ISSUE THREAD

**Issue by hsehweil** [awslabs/graphql-schema-utilities#11]
1.1.0-beta.0:
Issue:
GraphQL schema can have # or """ to leave a comment. with the 1.1.0-beta.0 only comments with """ are showing.

**Comment by hsehweil** [comment]
verified that issues is fixed in 1.1.0-beta.1

**Comment by kadishmal** [comment]
Should this issue be reopened? All single line comments are being converted into block comments which, unfortunately, is not supported in AWS AppSync GraphQL service.

This is why I write my comments in single lines so the AppSync accepts them.

I'm using:
- `"graphql-schema-utilities": "1.1.3",`
- `"graphql": "14.3.0",`
