### ISSUE TITLE
Errors when using LIST of mutations in @aws_subscribe

### ISSUE THREAD

**Issue by DanielGuelfi** [awslabs/graphql-schema-utilities#17]
Hi,
I am facing a "Could not merge Schema files!" error when trying to merge Subscriptions that contain the @aws_subscribe directive that expects a list of Strings as the "mutations" value.

The following directive has been defined in a file called "aws_appsync.graphql":
`directive @aws_subscribe(mutations: [String!]!) on FIELD_DEFINITION`

And Subscriptions defined in another as:
````
type Subscription {
    onCreate: Insight @aws_subscribe(mutations: ["createInsight"])
}
````

Behaviour:
- When calling the command "graphql-schema-utilities" without the "includeDirectives" flag, the merge completes successfully, but obviously does not includes any directives
- When calling the command with the "includeDirectives" flag, I receive the "Could not merge Schema files!" error
- If the "mutations" value is changed to a String, and the "includeDirectives" flag is set, for example:
`onCreate: Insight @aws_subscribe(mutations: "createInsight")`
Then the merge completes successfully.

The issue is I have a onUpdate subscription that needs to be triggered based on multiple mutation events, so the "mutations" value needs to be a list.

Thanks.

**Comment by hsehweil** [comment]
Looking into it.  The original printSchema code from graphql-js doesn’t support directives so a contribution was made to add that support, but it looks like there are some cases that are not handled.  We are looking into the feasibility of adding that in.  We also take contributions 🙂

**Comment by shenoyirvine** [comment]
We added a fix to support List arguments in Directives (contributed by @mattdhart). Please install the latest version and try it out.

**Comment by DanielGuelfi** [comment]
Thank you @mattdhart and @shenoyirvine. Have tested it with my schema and works perfectly. Really appreciate the super quick fix. Great job.
