### ISSUE TITLE
Empty type Query as mentioned in example not possible

### ISSUE THREAD

**Issue by andidev** [awslabs/graphql-schema-utilities#22]
Not possible to have an empty Root.graphql file with type Query as mentioned in example

https://aws.amazon.com/blogs/mobile/merging-graphql-schema-files-and-more-with-the-cli/

this is the error:

```bash
Loading schema from src/graphql/**/*.graphql
>> Error(1): Syntax Error: Expected Name, found } check the file:
file:///Users/**********/src/graphql/Root.graphql

Location of errors:  [ [ { line: 2, column: 1 } ] ]
>> Total numbers of errors found: 1.
Could not merge Schema files!
```

also in the blogpost this command is not complete:
```
> graphql-schema-utilities -s “{/module2/schemas/**/*.graphql,/module1/schemas/**/*.graphql,/moduleMain/schemas/**/*.graphql
```

**Comment by andidev** [comment]
okey I get it
```
type Query {     
}
```

must be defined as 
```
type Query
```

please update blog with both errrors

**Comment by fvilla-amazon** [comment]
You are correct on the type Query one.  It needs to be defined without curly braces.  We will look into getting the blog updated.  We will also look into the incomplete command.  It seems to be missing the trailing }" is that what you are referring to?

**Comment by brockgibson** [comment]
Hi @andidev we're looking into these now. Thanks for raising these issues.

**Comment by andidev** [comment]
@fvilla-amazon yes, and posible more is missing in that command.

**Comment by hsehweil** [comment]
thank you, updated documentations
